-- =================================================== PIZZA_SALES_ANALYSIS ========================================================


create table orders (
order_id int not null,
order_date date not null ,
order_time time not null,
primary key(order_id));

create table order_details (
order_details_id int not null,
order_id int not null ,
pizza_id text not null,    -- 48620 records
quantity int not null ,
primary key(order_details_id));


-- Basic: =========================================================================================================================

-- 1. Retrieve the total number of orders placed.-----------------------------------------------------------------------------------

SELECT 
    COUNT(*) AS Total_orders;

-- 2. Calculate the total revenue generated from pizza sales.----------------------------------------------------------------------
SELECT 
    round(sum(o.quantity*p.price),2)  AS Total_revenue
FROM
    order_details o
	JOIN
    pizzas p ON o.pizza_id = o.pizza_id;
    
-- 3. Identify the highest-priced pizza.--------------------------------------------------------------------------------------------
    
    SELECT 
    pt.name AS Pizza, p.price AS Price
FROM
    pizza_types pt
       left  JOIN
    pizzas p ON p.pizza_type_id = pt.pizza_type_id
    order by Price desc
    limit 1;
    
    
-- 4. Identify the most common pizza size ordered.----------------------------------------------------------------------------------

    SELECT 
    p.size AS Most_Common_Size,
    COUNT(o.order_details_id) AS Total_orders
FROM
    pizzas p
        JOIN
    order_details o ON o.pizza_id = p.pizza_id
GROUP BY p.size
ORDER BY Total_orders DESC
LIMIT 1;

-- 5. List the top 5 most ordered pizza types along with their quantities.----------------------------------------------------------

Select pt.name As Pizza , count(o.order_details_id) as Total_orders 
from order_details o 
join pizzas p
on p.pizza_id= o.pizza_id
join pizza_types pt 
on pt.pizza_type_id= p.pizza_type_id
group by Pizza 
order by Total_orders desc
limit 5;

-- Intermediate: ====================================================================================================================


-- 6. How does total revenue change month-wise?-------------------------------------------------------------------------------------

SELECT 
    EXTRACT(MONTH FROM o.order_date) AS month,
    SUM(od.quantity * p.price) AS revenue
FROM orders o
JOIN order_details od 
    ON o.order_id = od.order_id
JOIN pizzas p 
    ON od.pizza_id = p.pizza_id
GROUP BY month
ORDER BY month;

-- 7. Rank pizzas based on revenue.-------------------------------------------------------------------------------------------------

SELECT 
    pt.name,
    SUM(od.quantity * p.price) AS revenue,
    RANK() OVER (ORDER BY SUM(od.quantity * p.price) DESC) AS rank_no
FROM order_details od
JOIN pizzas p 
    ON od.pizza_id = p.pizza_id
JOIN pizza_types pt 
    ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.name;


-- 8. Join the necessary tables to find the total quantity of each pizza category ordered.------------------------------------------

Select pt.category as Pizza_Category , sum(o.quantity) as Total_Quantity 
from order_details o 
join pizzas p
on p.pizza_id= o.pizza_id
join pizza_types pt 
on pt.pizza_type_id= p.pizza_type_id
group by Pizza_Category
order by Total_Quantity desc;

-- 9. Determine the distribution of orders by hour of the day.------------------------------------------------------------------------

Select hour(order_time) as Hour_of_day , count(order_id) as Total_orders
from orders 
group by Hour_of_day
order by Total_orders desc;

-- 10. Join relevant tables to find the category-wise distribution of pizzas.--------------------------------------------------------

SELECT 
    category, COUNT(name) AS Pizza_distribution
FROM
    pizza_types
GROUP BY category; 


-- 11. Group the orders by date and calculate the average number of pizzas ordered per day.--------------------------------------------------------

SELECT 
    o.order_date, SUM(od.Quantity) AS Total_pizzas
FROM
    orders o
        JOIN
    order_details od ON od.order_id = o.order_id
GROUP BY order_date
ORDER BY Total_pizzas DESC;


-- Advance: =========================================================================================================================


-- 12. Find the total revenue generated by each pizza and display only those pizzas whose revenue is more than 5000.-------------------

WITH pizza_revenue AS (
    SELECT 
        pt.name AS pizza_name,
        SUM(od.quantity * p.price) AS total_revenue
    FROM order_details od
    JOIN pizzas p 
        ON od.pizza_id = p.pizza_id
    JOIN pizza_types pt 
        ON p.pizza_type_id = pt.pizza_type_id
    GROUP BY pt.name
)

SELECT 
    pizza_name,
    total_revenue
FROM pizza_revenue
WHERE total_revenue > 5000
ORDER BY total_revenue DESC;

-- 13. Determine the top 3 most ordered pizza types based on revenue.---------------------------------------------------------------

SELECT 
    pizza_types.name AS Pizza,
    SUM(order_details.quantity * pizzas.price) AS Total_revenue
FROM
    order_details
        JOIN
    pizzas ON pizzas.pizza_id = order_details.pizza_id
        JOIN
    pizza_types ON pizza_types.pizza_type_id = pizzas.pizza_type_id
GROUP BY Pizza
ORDER BY Total_revenue DESC;


-- 14. Calculate the percentage contribution of each pizza type to total revenue.---------------------------------------------------

SELECT 
    pt.name AS pizza_type,
    ROUND(
        SUM(od.quantity * p.price) 
        / (SELECT SUM(od2.quantity * p2.price)
           FROM order_details od2
           JOIN pizzas p2 ON od2.pizza_id = p2.pizza_id
          ) * 100, 
        2
    ) AS revenue_percentage
FROM order_details od
JOIN pizzas p ON od.pizza_id = p.pizza_id
JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.name
ORDER BY revenue_percentage DESC;

-- 15. Analyze the cumulative revenue generated over time.--------------------------------------------------------------------------

SELECT
    order_date,
    ROUND(
        SUM(daily_revenue) OVER (ORDER BY order_date),
        2
    ) AS cumulative_revenue
FROM (
    SELECT 
        o.order_date,
        SUM(od.quantity * p.price) AS daily_revenue
    FROM orders o
    JOIN order_details od ON o.order_id = od.order_id
    JOIN pizzas p ON od.pizza_id = p.pizza_id
    GROUP BY o.order_date
) t
ORDER BY order_date;

-- 16. Determine the top 3 most ordered pizza types based on revenue for each pizza category.--------------------------------------

SELECT
    category,
    pizza_type,
    revenue
FROM (
    SELECT
        pt.category,
        pt.name AS pizza_type,
        SUM(od.quantity * p.price) AS revenue,
        DENSE_RANK() OVER (
            PARTITION BY pt.category
            ORDER BY SUM(od.quantity * p.price) DESC
        ) AS rank_in_category
    FROM order_details od
    JOIN pizzas p ON od.pizza_id = p.pizza_id
    JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
    GROUP BY pt.category, pt.name
) ranked_pizzas
WHERE rank_in_category <= 3
ORDER BY category, revenue DESC;


-- 17. Find total orders per day and show only days with more than 100 orders.-----------------------------------------------------

WITH daily_orders AS (
    SELECT 
        order_date,
        COUNT(DISTINCT order_id) AS total_orders
    FROM orders
    GROUP BY order_date
)

SELECT *
FROM daily_orders
WHERE total_orders > 100
ORDER BY total_orders DESC;

-- 18. Rank months based on total revenue.------------------------------------------------------------------------------------------
SELECT 
    EXTRACT(MONTH FROM o.order_date) AS month,
    SUM(od.quantity * p.price) AS revenue,
    RANK() OVER (ORDER BY SUM(od.quantity * p.price) DESC) AS month_rank
FROM orders o
JOIN order_details od 
    ON o.order_id = od.order_id
JOIN pizzas p 
    ON od.pizza_id = p.pizza_id
GROUP BY month;


-- =============================================================End of Code.====================================================================







